import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { styles } from './styles';
import { ATSRuleResult } from '../ats';

export interface ReportData {
  resumeName: string;
  analysisDate: string;
  atsScore: number;
  overallRating: string;
  summary: string;
  strengths: string[];
  weaknesses: string[];
  missingTechnicalSkills: string[];
  missingSoftSkills: string[];
  grammarIssues: string[];
  formattingSuggestions: string[];
  improvementSuggestions: string[];
  recommendedJobRoles: string[];
  jobMatchScore: number | null;
  jobDescription?: string | null;
  atsBreakdown: ATSRuleResult['breakdown'];
  missingKeywords?: string[];
}

const PageFooter = () => (
  <View style={styles.footer} fixed>
    <Text style={styles.footerText}>Generated by AI Resume Analyzer | Version 1.0</Text>
    <Text style={styles.footerText}>© {new Date().getFullYear()} Dinesh Babu. All Rights Reserved.</Text>
    <Text style={styles.footerText} render={({ pageNumber, totalPages }) => (
      `Page ${pageNumber} of ${totalPages}`
    )} />
  </View>
);

export const ReportDocument = ({ data }: { data: ReportData }) => {
  const renderList = (items: string[]) => {
    if (!items || items.length === 0) {
      return <Text style={[styles.textNormal, { fontStyle: 'italic', color: '#9ca3af' }]}>None found</Text>;
    }
    return items.map((item, index) => (
      <View key={index} style={styles.listItem}>
        <Text style={styles.bulletPoint}>•</Text>
        <Text style={styles.listItemContent}>{item}</Text>
      </View>
    ));
  };

  const renderBadges = (items: string[], type: 'default' | 'warning' | 'success' = 'default') => {
    if (!items || items.length === 0) return null;
    return (
      <View style={styles.badgesContainer}>
        {items.map((item, index) => (
          <Text 
            key={index} 
            style={[
              styles.badge, 
              type === 'warning' ? styles.badgeWarning : {},
              type === 'success' ? styles.badgeSuccess : {},
            ]}
          >
            {item}
          </Text>
        ))}
      </View>
    );
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View>
            <Text style={styles.logoText}>AI Resume Analyzer</Text>
            <Text style={styles.logoSubtext}>Professional Resume Analysis Report</Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.title}>{data.resumeName}</Text>
            <Text style={styles.subtitle}>Analyzed on {data.analysisDate}</Text>
          </View>
        </View>

        {/* Scores */}
        <View style={styles.scoreRow}>
          <View style={styles.scoreBox}>
            <Text style={styles.scoreValue}>{data.atsScore}</Text>
            <Text style={styles.scoreLabel}>ATS Match Score</Text>
          </View>
          {data.jobMatchScore !== null && (
            <View style={styles.scoreBox}>
              <Text style={styles.scoreValue}>{data.jobMatchScore}</Text>
              <Text style={styles.scoreLabel}>Job Match Score</Text>
            </View>
          )}
        </View>

        {/* ATS Breakdown */}
        <View style={styles.card}>
          <Text style={styles.sectionTitle}>ATS Breakdown</Text>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Contact Information</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.contact} / 10</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Professional Summary</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.summary} / 10</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Education</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.education} / 10</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Skills</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.skills} / 15</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Projects</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.projects} / 15</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Experience</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.experience} / 20</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Certifications</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.certifications} / 5</Text>
          </View>
          <View style={styles.breakdownRow}>
            <Text style={styles.breakdownLabel}>Keyword Coverage</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.keywords} / 10</Text>
          </View>
          <View style={[styles.breakdownRow, { borderBottomWidth: 0 }]}>
            <Text style={styles.breakdownLabel}>Formatting</Text>
            <Text style={styles.breakdownScore}>{data.atsBreakdown.formatting} / 5</Text>
          </View>
        </View>

        {/* Executive Summary */}
        <View style={styles.section} wrap={false}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <Text style={styles.textNormal}>{data.summary}</Text>
        </View>

        <PageFooter />
      </Page>

        {/* Details Pages */}
      <Page size="A4" style={styles.page}>
        <View style={styles.header} fixed>
          <View>
            <Text style={styles.logoText}>AI Resume Analyzer</Text>
          </View>
          <View style={styles.headerRight}>
            <Text style={styles.title}>{data.resumeName}</Text>
          </View>
        </View>

        {/* Job Description Matching */}
        {data.jobMatchScore !== null && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Job Description Matching</Text>
            <Text style={[styles.textNormal, { marginBottom: 10 }]}>Job Match Score: {data.jobMatchScore} / 100</Text>
            
            {data.missingKeywords && data.missingKeywords.length > 0 && (
              <View style={{ marginBottom: 10 }}>
                <Text style={[styles.textNormal, { fontWeight: 'bold', marginBottom: 4 }]}>Missing Keywords from JD</Text>
                {renderBadges(data.missingKeywords, 'warning')}
              </View>
            )}
          </View>
        )}

        {/* Strengths */}
        {data.strengths.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Strengths</Text>
            {renderList(data.strengths)}
          </View>
        )}

        {/* Weaknesses */}
        {data.weaknesses.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={[styles.sectionTitle, { color: styles.badgeWarning.color }]}>Weaknesses</Text>
            {renderList(data.weaknesses)}
          </View>
        )}

        {/* Missing Technical Skills */}
        {data.missingTechnicalSkills.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Missing Technical Skills</Text>
            {renderBadges(data.missingTechnicalSkills, 'warning')}
          </View>
        )}

        {/* Missing Soft Skills */}
        {data.missingSoftSkills.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Missing Soft Skills</Text>
            {renderBadges(data.missingSoftSkills, 'warning')}
          </View>
        )}

        {/* Grammar & Formatting */}
        {(data.grammarIssues.length > 0 || data.formattingSuggestions.length > 0) && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Formatting & Grammar</Text>
            {renderList([...data.formattingSuggestions, ...data.grammarIssues])}
          </View>
        )}

        {/* Recommendations */}
        {data.improvementSuggestions.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Improvement Suggestions</Text>
            {renderList(data.improvementSuggestions)}
          </View>
        )}

        {/* Recommended Job Roles */}
        {data.recommendedJobRoles.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Recommended Job Roles</Text>
            {renderBadges(data.recommendedJobRoles, 'success')}
          </View>
        )}

        <PageFooter />
      </Page>
    </Document>
  );
};
